### ISSUE TITLE
Gymnasium Upgrade

### ISSUE THREAD

**Issue by jkterry1** [MatPoliquin/stable-retro#5]
Hi! We've spoken briefly before, but I've been the maintainer of Gym for the past ~2 years. Would you be willing to update this repo to use Gymnasium? You can read more about the details and backstory here: https://farama.org/Announcing-The-Farama-Foundation

**Comment by victorsevero** [comment]
I'm not a contributor of this project, but I'd be glad to help making this happen. I've been looking forward to a `retro`'s successor and this fork seems the most promising.

**Comment by jkterry1** [comment]
If you'd be willing to do a PR for this that'd be really awesome :)

**Comment by victorsevero** [comment]
@jkterry1 if you could, I would love to have your review (or from anyone from Farama) in this PR!

**Comment by jkterry1** [comment]
Closed by #7
